### ISSUE TITLE
[question] How to inject Genie?

### ISSUE THREAD

**Issue by ebuildy** [osglworks/java-di#40]
Question:

I want to retrieve created Genie in a service, how can I inject it?

**Comment by greenlaw110** [comment]
@ebuildy Genie is the entry to your DI world, you need only one copy of Genie instance across your application. You can use Singleton pattern to create something like `GenieManager` with a static method to get Genie instance. e.g. `GenieManager.genie()`.

Basically use `Genie` in the same way you use [Guice Injector](https://github.com/google/guice/wiki/GettingStarted).

**Comment by ebuildy** [comment]
Thanks you, also I guess injecting injector is not a good practice and should be avoided, so I will read doc more carefully to find the good way to achieve what I want.
